/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import database.DBConnection;
import java.awt.HeadlessException;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author mayan
 */
public class admin extends javax.swing.JFrame {

    /**
     * Creates new form teach
     */
    public admin() {
        initComponents();
        oldtf.setEditable(false);
        feepaidtf.setEditable(false);

    }
        DBConnection db=new DBConnection();
        Connection conn=db.getMysqlConnect();
        public static int prnStudPool=103217190;
        public static int prnTeachPool=103517190;
       private int prn;
       admin(int prn) {
           prnStudPool+=1;
           prnTeachPool+=1;
            initComponents();
        feepaidtf.setEditable(false);
            oldtf.setEditable(false);
            this.prn=prn;
       }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newuser = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        ptf = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        addnewuser = new javax.swing.JButton();
        passtf = new javax.swing.JTextField();
        strb = new javax.swing.JRadioButton();
        trb = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        usertype = new javax.swing.ButtonGroup();
        chngepassword = new javax.swing.JDialog();
        old = new javax.swing.JTextField();
        newp = new javax.swing.JTextField();
        confirmnewp = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        chnge = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        ch_att = new javax.swing.JDialog();
        subselect = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        pr_rb = new javax.swing.JRadioButton();
        th_rb = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        updateatt = new javax.swing.JButton();
        oldtf = new javax.swing.JTextField();
        newtf = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        display = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        prntf = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        classtype = new javax.swing.ButtonGroup();
        deluser = new javax.swing.JDialog();
        delprntf = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        del = new javax.swing.JButton();
        updfees = new javax.swing.JDialog();
        jLabel12 = new javax.swing.JLabel();
        fprntf = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        feetf = new javax.swing.JTextField();
        Update = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        feepaidtf = new javax.swing.JTextField();
        data = new javax.swing.JButton();
        choice = new javax.swing.ButtonGroup();
        addNoticeRadio = new javax.swing.JRadioButton();
        changePassRadio = new javax.swing.JRadioButton();
        proceed = new javax.swing.JButton();
        updateSalaryRadio = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        addStud = new javax.swing.JRadioButton();
        deleteUserRadio = new javax.swing.JRadioButton();
        jLabel17 = new javax.swing.JLabel();
        addTeacher = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        updateFeesRadio = new javax.swing.JRadioButton();
        ChangeAttendanceRadio = new javax.swing.JRadioButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        logout = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();

        newuser.setTitle("ADD NEW USER");
        newuser.setBounds(new java.awt.Rectangle(400, 300, 480, 260));
        newuser.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setText("New PRN :-");

        jLabel2.setText("New Password :-");

        addnewuser.setText("ADD DETAILS");
        addnewuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addnewuserActionPerformed(evt);
            }
        });

        usertype.add(strb);
        strb.setText("Student");

        usertype.add(trb);
        trb.setText("Teacher");

        jLabel10.setText("(max value 2147483647)");

        javax.swing.GroupLayout newuserLayout = new javax.swing.GroupLayout(newuser.getContentPane());
        newuser.getContentPane().setLayout(newuserLayout);
        newuserLayout.setHorizontalGroup(
            newuserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newuserLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addnewuser, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(122, 122, 122))
            .addGroup(newuserLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(strb)
                .addGap(92, 92, 92)
                .addComponent(trb)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newuserLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(newuserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(newuserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(passtf, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ptf, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76))
        );
        newuserLayout.setVerticalGroup(
            newuserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newuserLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(newuserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(strb)
                    .addComponent(trb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(6, 6, 6)
                .addGroup(newuserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ptf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(newuserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passtf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(addnewuser, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        chngepassword.setTitle("Change Password");
        chngepassword.setBounds(new java.awt.Rectangle(450, 300, 450, 270));

        jLabel4.setText("Old Password :-");

        jLabel5.setText("New Password :-");

        jLabel6.setText("Confirm New Password :-");

        chnge.setText("Change");
        chnge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chngeActionPerformed(evt);
            }
        });

        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout chngepasswordLayout = new javax.swing.GroupLayout(chngepassword.getContentPane());
        chngepassword.getContentPane().setLayout(chngepasswordLayout);
        chngepasswordLayout.setHorizontalGroup(
            chngepasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, chngepasswordLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(chngepasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(chngepasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(newp, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                    .addComponent(confirmnewp)
                    .addComponent(old))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, chngepasswordLayout.createSequentialGroup()
                .addContainerGap(240, Short.MAX_VALUE)
                .addComponent(clear)
                .addGap(18, 18, 18)
                .addComponent(chnge)
                .addGap(72, 72, 72))
        );
        chngepasswordLayout.setVerticalGroup(
            chngepasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chngepasswordLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(chngepasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(old, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(chngepasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newp, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(chngepasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmnewp, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(34, 34, 34)
                .addGroup(chngepasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chnge)
                    .addComponent(clear))
                .addGap(60, 60, 60))
        );

        ch_att.setTitle("Alter Attendance");
        ch_att.setBounds(new java.awt.Rectangle(200, 300, 540, 350));

        subselect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Subject", "TOC", "CN", "DBMS", "SMD" }));
        subselect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subselectActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(), null));
        jPanel1.setName(""); // NOI18N

        classtype.add(pr_rb);
        pr_rb.setText("Practical");
        pr_rb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pr_rbActionPerformed(evt);
            }
        });

        classtype.add(th_rb);
        th_rb.setText("Theory");
        th_rb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                th_rbActionPerformed(evt);
            }
        });

        jLabel3.setText("Class Type");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pr_rb)
                    .addComponent(jLabel3)
                    .addComponent(th_rb))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(th_rb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pr_rb)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        updateatt.setText("Update Attendance");
        updateatt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateattActionPerformed(evt);
            }
        });

        jLabel7.setText("Old attendance :-");

        display.setText("Display");
        display.setEnabled(false);
        display.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayActionPerformed(evt);
            }
        });

        jLabel8.setText("New attendance :-");

        jLabel9.setText("PRN :-");

        javax.swing.GroupLayout ch_attLayout = new javax.swing.GroupLayout(ch_att.getContentPane());
        ch_att.getContentPane().setLayout(ch_attLayout);
        ch_attLayout.setHorizontalGroup(
            ch_attLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ch_attLayout.createSequentialGroup()
                .addGroup(ch_attLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ch_attLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(ch_attLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ch_attLayout.createSequentialGroup()
                                .addGroup(ch_attLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addGap(18, 18, 18)
                                .addGroup(ch_attLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(newtf, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(ch_attLayout.createSequentialGroup()
                                        .addComponent(oldtf, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(40, 40, 40)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(ch_attLayout.createSequentialGroup()
                                .addComponent(display)
                                .addGap(106, 106, 106)
                                .addComponent(updateatt))))
                    .addGroup(ch_attLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(prntf, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(subselect, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(119, Short.MAX_VALUE))
        );
        ch_attLayout.setVerticalGroup(
            ch_attLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ch_attLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(ch_attLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ch_attLayout.createSequentialGroup()
                        .addGroup(ch_attLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ch_attLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(prntf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9))
                            .addGroup(ch_attLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(subselect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(37, 37, 37)
                        .addGroup(ch_attLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(oldtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(49, 49, 49)
                        .addGroup(ch_attLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(newtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addGroup(ch_attLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateatt)
                    .addComponent(display))
                .addGap(57, 57, 57))
        );

        deluser.setTitle("Delete User");
        deluser.setBounds(new java.awt.Rectangle(450, 350, 350, 200));

        jLabel11.setText("PRN :-");

        del.setText("Delete");
        del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout deluserLayout = new javax.swing.GroupLayout(deluser.getContentPane());
        deluser.getContentPane().setLayout(deluserLayout);
        deluserLayout.setHorizontalGroup(
            deluserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deluserLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel11)
                .addGap(48, 48, 48)
                .addComponent(delprntf, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deluserLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(del)
                .addGap(65, 65, 65))
        );
        deluserLayout.setVerticalGroup(
            deluserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deluserLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(deluserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(delprntf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(35, 35, 35)
                .addComponent(del)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        updfees.setTitle("Update Fees Data");
        updfees.setBounds(new java.awt.Rectangle(450, 350, 450, 250));

        jLabel12.setText("PRN :-");

        jLabel13.setText(" Fees Amount :-");

        Update.setText("Update Fees");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });

        jLabel14.setText(" Fees Paid :-");

        feepaidtf.setEditable(false);

        data.setText("Get Data");
        data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout updfeesLayout = new javax.swing.GroupLayout(updfees.getContentPane());
        updfees.getContentPane().setLayout(updfeesLayout);
        updfeesLayout.setHorizontalGroup(
            updfeesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, updfeesLayout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addGroup(updfeesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, updfeesLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(data)
                        .addGap(12, 12, 12))
                    .addGroup(updfeesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(updfeesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(updfeesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(updfeesLayout.createSequentialGroup()
                                    .addComponent(jLabel14)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(feepaidtf, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, updfeesLayout.createSequentialGroup()
                                    .addComponent(jLabel13)
                                    .addGap(66, 66, 66)
                                    .addComponent(feetf, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, updfeesLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Update)
                                .addGap(45, 45, 45)))
                        .addGroup(updfeesLayout.createSequentialGroup()
                            .addComponent(jLabel12)
                            .addGap(113, 113, 113)
                            .addComponent(fprntf, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(53, 53, 53))
        );
        updfeesLayout.setVerticalGroup(
            updfeesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, updfeesLayout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addGroup(updfeesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(fprntf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(data)
                .addGap(18, 18, 18)
                .addGroup(updfeesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(feepaidtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(updfeesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(feetf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addComponent(Update)
                .addGap(21, 21, 21))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 229, 155));
        setForeground(new java.awt.Color(154, 200, 130));
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(670, 540));
        setMinimumSize(new java.awt.Dimension(670, 540));
        setPreferredSize(new java.awt.Dimension(670, 540));
        getContentPane().setLayout(null);

        choice.add(addNoticeRadio);
        addNoticeRadio.setText("Add Notice");
        getContentPane().add(addNoticeRadio);
        addNoticeRadio.setBounds(89, 351, 77, 49);

        choice.add(changePassRadio);
        changePassRadio.setText("Change Password");
        getContentPane().add(changePassRadio);
        changePassRadio.setBounds(239, 351, 111, 49);

        proceed.setText("Proceed");
        proceed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proceedActionPerformed(evt);
            }
        });
        getContentPane().add(proceed);
        proceed.setBounds(212, 425, 167, 32);

        choice.add(updateSalaryRadio);
        updateSalaryRadio.setText("Update Salary");
        updateSalaryRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateSalaryRadioActionPerformed(evt);
            }
        });
        getContentPane().add(updateSalaryRadio);
        updateSalaryRadio.setBounds(408, 351, 93, 49);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        choice.add(addStud);
        addStud.setText("Add Student");

        choice.add(deleteUserRadio);
        deleteUserRadio.setText("Delete User");

        jLabel17.setText("User operations");

        addTeacher.setText("Add Teacher");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addGap(177, 177, 177))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(addStud)
                        .addGap(64, 64, 64)
                        .addComponent(addTeacher))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(deleteUserRadio)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addStud)
                    .addComponent(addTeacher))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(deleteUserRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(89, 75, 418, 112);

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        choice.add(updateFeesRadio);
        updateFeesRadio.setText("Update Fees");

        choice.add(ChangeAttendanceRadio);
        ChangeAttendanceRadio.setText("Change Attendnace");

        jLabel18.setText("Student Opertions");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(155, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(updateFeesRadio)
                    .addComponent(ChangeAttendanceRadio))
                .addGap(138, 138, 138))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addGap(18, 18, 18)
                .addComponent(ChangeAttendanceRadio)
                .addGap(17, 17, 17)
                .addComponent(updateFeesRadio)
                .addContainerGap())
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(89, 198, 418, 117);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 204));
        jLabel19.setText("ADMIN");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(261, 6, 154, 58);

        logout.setText("logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        getContentPane().add(logout);
        logout.setBounds(530, 11, 63, 23);

        jLabel15.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Desktop\\back1.jpg")); // NOI18N
        jLabel15.setMaximumSize(new java.awt.Dimension(780, 540));
        jLabel15.setMinimumSize(new java.awt.Dimension(780, 540));
        jLabel15.setPreferredSize(new java.awt.Dimension(780, 540));
        getContentPane().add(jLabel15);
        jLabel15.setBounds(0, -20, 780, 540);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addnewuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addnewuserActionPerformed
        if(strb.isSelected() || trb.isSelected()){
            if(ptf.getText().isEmpty() || passtf.getText().isEmpty()){
                JOptionPane.showMessageDialog (null, "EMPTY FIELDS !!!!!", "Try again", JOptionPane.INFORMATION_MESSAGE);
            }
            else{
                String qry, qry1,qry2;
                try {

                    Statement stmt=conn.createStatement();
                    qry="insert into user(prn, password) values("+Integer.parseInt(ptf.getText())+", \""+passtf.getText()+"\");";
                    stmt.executeUpdate(qry);
                    if( Integer.parseInt(ptf.getText())>1032099999 && Integer.parseInt(ptf.getText())<1032300000)
                    {
                        if(strb.isSelected()){
                            qry1="insert into student(prn) values("+Integer.parseInt(ptf.getText())+");";
                            qry2="insert into attendance(prn) values("+Integer.parseInt(ptf.getText())+");";
                            stmt.executeUpdate(qry1);
                            stmt.executeUpdate(qry2);
                            newstud stud=new newstud(Integer.parseInt(ptf.getText()));
                            this.dispose();
                            stud.setVisible(true);
                        }
                        else{
                            qry1="insert into teachers(prn) values("+Integer.parseInt(ptf.getText())+");";
                            stmt.executeUpdate(qry1);
                            newteacher teach=new newteacher(Integer.parseInt(ptf.getText()));
                            this.dispose();
                            teach.setVisible(true);
                        }
                    }
                    else
                        JOptionPane.showMessageDialog (null, "Check the entries again", "Error", JOptionPane.ERROR_MESSAGE);
                } catch (SQLException | HeadlessException | NumberFormatException ex) {
                    Logger.getLogger(updateProfile.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        else
             JOptionPane.showMessageDialog (null, "Enter user type !!!!", "Error", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_addnewuserActionPerformed

    private void chngeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chngeActionPerformed
        try {
            Statement stmt=conn.createStatement();
            String pass="";
            String qry="select pass from user where prn="+prn+";", qry1;
            ResultSet rs=stmt.executeQuery(qry);
            pass=rs.getString("pass");
            if(pass.equals(old.getText())){
                if(newp.getText().equals(confirmnewp.getText())){
                    qry1="update user set pass=\""+newp.getText()+"\" where prn="+prn+";";
                    stmt.executeUpdate(qry1);
                    JOptionPane.showMessageDialog(null, "Password chnged successfully...!!!", "DONE", 3);
                }
                else
                JOptionPane.showMessageDialog(null, "New pasawords doesnt match...!!!", "ERROR", 1);
            }
            else
            JOptionPane.showMessageDialog(null, "Old password entered incorrect...!!!", "ERROR", 1);
        } catch (SQLException ex) {
            Logger.getLogger(teacher.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_chngeActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        old.setText("");
        newp.setText("");
        confirmnewp.setText("");
    }//GEN-LAST:event_clearActionPerformed
        
    private void updateattActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateattActionPerformed
        try {
            int prns=Integer.parseInt(prntf.getText());

            Statement stmt=conn.createStatement();
            String sub="",ctype="";
            int sub_in;
            sub_in=subselect.getSelectedIndex();
            if(th_rb.isSelected() || pr_rb.isSelected()){
                if(th_rb.isSelected()){
                    ctype="t";
                }
                else if(pr_rb.isSelected()){
                    ctype="p";
                }
                if(subselect.getSelectedIndex()!=0){
                    switch(sub_in){
                        case 1: {
                            sub="toc";
                            break;
                        }
                        case 2: {
                            sub="cn";
                            break;
                        }       
                        case 3: {
                            sub="dbms";
                            break;
                        }
                        case 4: {
                            sub="smd";
                            break;
                        }
                        default: JOptionPane.showMessageDialog(null, "Select Subject !!!!!", "ERROR", 1);
                    }
                   
                    int updatedAtt=Integer.valueOf(newtf.getText());
                    
                    String qry="update attendance set "+ctype+sub+"="+updatedAtt+" where prn="+prns+";";
//                    String qry="update attendance set "+sub+"_"+ctype+"="+newtf.getText()+" where prn="+prntf.getText()+";";
                    stmt.executeUpdate(qry);
                    JOptionPane.showMessageDialog(null, "CHANGED SUCCESSFULLY !!!!!", "Done", 3);
                }
                else
                    JOptionPane.showMessageDialog(null, "Select subject !!!!!", "ERROR", 1);
            }
            else
                JOptionPane.showMessageDialog(null, "Select Class Type !!!!!", "ERROR", 1);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,"user with entered prn not found","try again",JOptionPane.ERROR_MESSAGE);
            
        }catch(NumberFormatException ex){
                JOptionPane.showMessageDialog(rootPane,"enter valid new attendance or prn","try again",JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_updateattActionPerformed
        
    private void displayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayActionPerformed
        try {
            int prns=Integer.parseInt(prntf.getText());
            
            Statement stmt=conn.createStatement();
            String sub="",ctype="";
            int sub_in;
            sub_in=subselect.getSelectedIndex();
            if(th_rb.isSelected() || pr_rb.isSelected()){
                if(th_rb.isSelected()){
                    ctype="t";
                }
                else if(pr_rb.isSelected()){
                    ctype="p";
                }
                switch(sub_in){
                    case 1: {
                        sub="toc";
                        break;
                    }
                    case 2: {
                        sub="cn";
                        break;
                    }       
                    case 3: {
                        sub="dbms";
                        break;
                    }
                    case 4: {
                        sub="smd";
                        break;
                    }
                    default: JOptionPane.showMessageDialog(null, "Select Subject !!!!!", "ERROR", 1);
                }            
            String qry="select "+ctype+sub+" from attendance where prn="+prns+";";
            ResultSet rs=stmt.executeQuery(qry);
            if(rs.next()){
            oldtf.setText(String.valueOf(rs.getInt(ctype+sub)));
            }
            }
            else
                JOptionPane.showMessageDialog(null, "Select Class Type !!!!!", "ERROR", 1);
        }
        catch (SQLException ex) {
            Logger.getLogger(admin.class.getName()).log(Level.SEVERE, null, ex);
        }catch(NumberFormatException ex){
                JOptionPane.showMessageDialog(rootPane,"enter valid new attendance or prn","try again",JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_displayActionPerformed

    private void subselectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subselectActionPerformed
        if(th_rb.isSelected() || pr_rb.isSelected()){
            display.setEnabled(true);
        }
        else
            display.setEnabled(false);
    }//GEN-LAST:event_subselectActionPerformed

    private void th_rbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_th_rbActionPerformed
        if(subselect.getSelectedIndex()!=0 || pr_rb.isSelected()){
            display.setEnabled(true);
        }
        else
            display.setEnabled(false);
    }//GEN-LAST:event_th_rbActionPerformed

    private void pr_rbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pr_rbActionPerformed
        if(th_rb.isSelected() || subselect.getSelectedIndex()!=0){
            display.setEnabled(true);
        }
        else
            display.setEnabled(false);
    }//GEN-LAST:event_pr_rbActionPerformed

    private void delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delActionPerformed
        try {
            int delprn=Integer.parseInt(delprntf.getText());
            Statement stmt=conn.createStatement();
            String qry="delete from user where prn="+delprn+";";
            stmt.executeUpdate(qry);
            JOptionPane.showMessageDialog(null, "User DELETED !!!!!", "Success", 3);
        } catch (HeadlessException | NumberFormatException | SQLException ex) {
            Logger.getLogger(admin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_delActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        try {
            int fprn=Integer.parseInt(fprntf.getText());
            int fee=Integer.parseInt(feetf.getText());
            Statement stmt=conn.createStatement();
            String qry="select fees_paid from stud where prn="+fprn+";";
            ResultSet rs=stmt.executeQuery(qry);
            int paid=rs.getInt("fees_paid");
            int total=fee+paid;
            if(total>260000){
                JOptionPane.showMessageDialog(null, "Wrong Amount !!!!!", "ERROR", 1);
            }
            else{
                String qry1="update stud set fees_paid="+total+";";
            }
        } catch (SQLException ex) {
            Logger.getLogger(admin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_UpdateActionPerformed

    private void dataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataActionPerformed
        try {
            int fprn=Integer.parseInt(fprntf.getText());
            Statement stmt=conn.createStatement();
            String qry="select fees_paid from stud where prn="+fprn+";";
            ResultSet rs=stmt.executeQuery(qry);
            if(rs.next()){
            feepaidtf.setText(Integer.toString(rs.getInt("fees_paid")));
            this.feetf.setText(Integer.toString(260000-rs.getInt("fees_paid")));
            }
        } catch (SQLException ex) {
            Logger.getLogger(admin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_dataActionPerformed

    private void updateSalaryRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateSalaryRadioActionPerformed

    }//GEN-LAST:event_updateSalaryRadioActionPerformed

    private void proceedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proceedActionPerformed
        if(changePassRadio.isSelected()){
            new passwordChange(this.prn).setVisible(true);
        }
        else if(addNoticeRadio.isSelected()){
            notices n=new notices();
            n.setVisible(true);
        }
        else if(ChangeAttendanceRadio.isSelected()){
            ch_att.setVisible(true);
        }
        else if(deleteUserRadio.isSelected()){
            deluser.setVisible(true);
        }
        else if(addStud.isSelected()){
            
            new newstud(prnStudPool).setVisible(true);
        }
        else if(addTeacher.isSelected()){
            new newteacher(prnTeachPool).setVisible(true);
        }
        else if(updateFeesRadio.isSelected()){
            updfees.setVisible(true);
        }
        else if(updateSalaryRadio.isSelected()){
            new updateSal().setVisible(true);
        }
    }//GEN-LAST:event_proceedActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        dispose();
        new login().setVisible(true);
    }//GEN-LAST:event_logoutActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new admin().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton ChangeAttendanceRadio;
    private javax.swing.JButton Update;
    private javax.swing.JRadioButton addNoticeRadio;
    private javax.swing.JRadioButton addStud;
    private javax.swing.JRadioButton addTeacher;
    private javax.swing.JButton addnewuser;
    private javax.swing.JDialog ch_att;
    private javax.swing.JRadioButton changePassRadio;
    private javax.swing.JButton chnge;
    private javax.swing.JDialog chngepassword;
    private javax.swing.ButtonGroup choice;
    private javax.swing.ButtonGroup classtype;
    private javax.swing.JButton clear;
    private javax.swing.JTextField confirmnewp;
    private javax.swing.JButton data;
    private javax.swing.JButton del;
    private javax.swing.JRadioButton deleteUserRadio;
    private javax.swing.JTextField delprntf;
    private javax.swing.JDialog deluser;
    private javax.swing.JButton display;
    private javax.swing.JTextField feepaidtf;
    private javax.swing.JTextField feetf;
    private javax.swing.JTextField fprntf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton logout;
    private javax.swing.JTextField newp;
    private javax.swing.JTextField newtf;
    private javax.swing.JDialog newuser;
    private javax.swing.JTextField old;
    private javax.swing.JTextField oldtf;
    private javax.swing.JTextField passtf;
    private javax.swing.JRadioButton pr_rb;
    private javax.swing.JTextField prntf;
    private javax.swing.JButton proceed;
    private javax.swing.JTextField ptf;
    private javax.swing.JRadioButton strb;
    private javax.swing.JComboBox<String> subselect;
    private javax.swing.JRadioButton th_rb;
    private javax.swing.JRadioButton trb;
    private javax.swing.JRadioButton updateFeesRadio;
    private javax.swing.JRadioButton updateSalaryRadio;
    private javax.swing.JButton updateatt;
    private javax.swing.JDialog updfees;
    private javax.swing.ButtonGroup usertype;
    // End of variables declaration//GEN-END:variables
}
