/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import database.DBConnection;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author mayan
 */
public class courseupdate extends javax.swing.JFrame {
            DBConnection db=new DBConnection();
            Connection conn=db.getMysqlConnect();
    /**
     * Creates new form 
     */
            private int prn;
    public courseupdate() {
        initComponents();
    }
   public courseupdate(int prn){
       initComponents();
                try {
                    String sub="";
                    
                    this.prn=prn;
                    String qry="select c.unit, c.topics,t.subject from course c, teacher t where t.subject=c.subject and t.prn="+prn+";";
                    System.out.println(qry);
                    Statement stmt=conn.createStatement();
                    ResultSet rs=stmt.executeQuery(qry);
                    while(rs.next()){
                        sub=rs.getString("subject");
                        System.out.println(sub);
                        switch(rs.getInt("unit")){
                            case 1:{
                                unit1ta.setText(rs.getString("topics"));
                                System.out.println(rs.getString("topics"));
                                break;
                            }
                            case 2:{
                                unit2ta.setText(rs.getString("topics"));
                                System.out.println(rs.getString("topics"));
                                break;
                            }
                            case 3:{
                                unit3ta.setText(rs.getString("topics"));
                                System.out.println(rs.getString("topics"));
                                break;
                            }
                            case 4:{
                                unit4ta.setText(rs.getString("topics"));
                                System.out.println(rs.getString("topics"));
                                break;
                            }
                            default: System.out.println("no course updated or available");
                        }
                    }
                }
                catch (SQLException ex) {
                    Logger.getLogger(courseupdate.class.getName()).log(Level.SEVERE, null, ex);
                }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        unit1ta = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        unit2ta = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        unit3ta = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        unit4ta = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        updatecourse = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(700, 600));
        setMinimumSize(new java.awt.Dimension(700, 600));
        setPreferredSize(new java.awt.Dimension(700, 600));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        jLabel1.setText("Unit 1 :-");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 70, 100, 27);

        unit1ta.setColumns(20);
        unit1ta.setLineWrap(true);
        unit1ta.setRows(5);
        unit1ta.setWrapStyleWord(true);
        unit1ta.setOpaque(false);
        jScrollPane1.setViewportView(unit1ta);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(180, 31, 313, 96);

        unit2ta.setColumns(20);
        unit2ta.setLineWrap(true);
        unit2ta.setRows(5);
        unit2ta.setWrapStyleWord(true);
        unit2ta.setOpaque(false);
        jScrollPane2.setViewportView(unit2ta);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(180, 145, 313, 96);

        jLabel2.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        jLabel2.setText("Unit 2 :-");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 180, 100, 27);

        unit3ta.setColumns(20);
        unit3ta.setLineWrap(true);
        unit3ta.setRows(5);
        unit3ta.setWrapStyleWord(true);
        unit3ta.setOpaque(false);
        jScrollPane3.setViewportView(unit3ta);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(180, 259, 313, 96);

        jLabel3.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        jLabel3.setText("Unit 3 :-");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 290, 100, 27);

        unit4ta.setColumns(20);
        unit4ta.setLineWrap(true);
        unit4ta.setRows(5);
        unit4ta.setWrapStyleWord(true);
        unit4ta.setOpaque(false);
        jScrollPane4.setViewportView(unit4ta);

        getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(180, 373, 313, 96);

        jLabel4.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        jLabel4.setText("Unit 4 :-");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 410, 110, 27);

        updatecourse.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        updatecourse.setText("Update Course");
        updatecourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatecourseActionPerformed(evt);
            }
        });
        getContentPane().add(updatecourse);
        updatecourse.setBounds(230, 490, 200, 40);

        back.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        back.setText("back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(510, 10, 100, 30);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces/wall.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        jLabel5.setMaximumSize(new java.awt.Dimension(780, 600));
        jLabel5.setMinimumSize(new java.awt.Dimension(780, 600));
        jLabel5.setPreferredSize(new java.awt.Dimension(780, 600));
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 780, 600);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void updatecourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatecourseActionPerformed
        String sub;
        try {
            String unit1=unit1ta.getText();
            String unit2=unit2ta.getText();
            String unit3=unit3ta.getText();
            String unit4=unit4ta.getText();
            Statement stmt=conn.createStatement();
            String qry="select subject from teacher where prn="+prn+";";
            ResultSet rs=stmt.executeQuery(qry);
            if(rs.next()){
            sub=rs.getString("subject");
            String qry1="update course set topics=\""+unit1+"\" where subject=\""+sub+"\" and unit=1;";
            String qry2="update course set topics=\""+unit2+"\" where subject=\""+sub+"\" and unit=2;";
            String qry3="update course set topics=\""+unit3+"\" where subject=\""+sub+"\" and unit=3;";
            String qry4="update course set topics=\""+unit4+"\" where subject=\""+sub+"\" and unit=4;"; 
            stmt.executeUpdate(qry1);
            stmt.executeUpdate(qry2);
            stmt.executeUpdate(qry3);
            stmt.executeUpdate(qry4);
            }


            JOptionPane.showMessageDialog(null, "Updated Successfully !!!!!", "Done", 3);
        } 
        catch (SQLException ex) {
            Logger.getLogger(courseupdate.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_updatecourseActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        dispose();
        new teacher(this.prn).setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(courseupdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(courseupdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(courseupdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(courseupdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new courseupdate(1035170113).setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea unit1ta;
    private javax.swing.JTextArea unit2ta;
    private javax.swing.JTextArea unit3ta;
    private javax.swing.JTextArea unit4ta;
    private javax.swing.JButton updatecourse;
    // End of variables declaration//GEN-END:variables
}
