/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import database.DBConnection;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author admin
 */
public class login extends javax.swing.JFrame {
    

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
    }

            DBConnection db=new DBConnection();
            Connection conn=db.getMysqlConnect();    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        label_username = new javax.swing.JLabel();
        label_password = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        submit = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        student = new javax.swing.JRadioButton();
        teacher = new javax.swing.JRadioButton();
        admin = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(240, 181, 70));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(new java.awt.Color(255, 167, 216));
        setMaximumSize(new java.awt.Dimension(780, 530));
        setMinimumSize(new java.awt.Dimension(780, 530));
        setPreferredSize(new java.awt.Dimension(780, 540));
        setSize(new java.awt.Dimension(780, 530));
        getContentPane().setLayout(null);

        label_username.setBackground(new java.awt.Color(240, 105, 94));
        label_username.setFont(new java.awt.Font("Verdana", 1, 20)); // NOI18N
        label_username.setText("Username");
        getContentPane().add(label_username);
        label_username.setBounds(210, 210, 153, 24);

        label_password.setFont(new java.awt.Font("Verdana", 1, 20)); // NOI18N
        label_password.setText("Password ");
        getContentPane().add(label_password);
        label_password.setBounds(210, 280, 127, 24);

        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        getContentPane().add(username);
        username.setBounds(400, 200, 200, 40);
        getContentPane().add(password);
        password.setBounds(400, 270, 200, 40);

        submit.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        submit.setText("Login");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        getContentPane().add(submit);
        submit.setBounds(250, 400, 95, 37);

        reset.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        getContentPane().add(reset);
        reset.setBounds(420, 400, 84, 37);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Documents\\java_projects\\erp-dbms\\images\\MIT-WPU-logo.png")); // NOI18N
        jLabel4.setMinimumSize(new java.awt.Dimension(500, 154));
        jLabel4.setPreferredSize(new java.awt.Dimension(500, 154));
        getContentPane().add(jLabel4);
        jLabel4.setBounds(150, 20, 500, 151);

        buttonGroup1.add(student);
        student.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        student.setSelected(true);
        student.setText("Student");
        student.setOpaque(false);
        getContentPane().add(student);
        student.setBounds(190, 350, 79, 31);

        buttonGroup1.add(teacher);
        teacher.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        teacher.setText("Teacher");
        teacher.setOpaque(false);
        getContentPane().add(teacher);
        teacher.setBounds(330, 350, 81, 31);

        buttonGroup1.add(admin);
        admin.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        admin.setText("Admin");
        admin.setOpaque(false);
        getContentPane().add(admin);
        admin.setBounds(470, 350, 71, 31);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces/wall.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setAlignmentY(0.0F);
        jLabel1.setMaximumSize(new java.awt.Dimension(780, 540));
        jLabel1.setMinimumSize(new java.awt.Dimension(780, 540));
        jLabel1.setPreferredSize(new java.awt.Dimension(780, 540));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -220, 780, 740);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        try {
                int user=0;
                user = Integer.parseInt(username.getText());

                studenthomepage home;
                teacher teach;
                admin ad;
                String pass=password.getText();

                Statement stmt=conn.createStatement();

                ResultSet rst=stmt.executeQuery("select prn,password from user where prn="+user+";");

                if(rst.next()){
                    int prn=rst.getInt("prn");
                    String pass1=rst.getString("password");
                    if(user==prn && pass.equals(pass1)){
                    if(student.isSelected() && prn>103217000 && prn<103217999){
                    home=new studenthomepage(prn);
                    
                    home.setVisible(true);
                    this.dispose();
                    JOptionPane.showMessageDialog(null, "You logged in successfully as student..!!!");  
                    }
                    
                    else if(teacher.isSelected() && prn>1035170000 && prn<1035179999 ){
                        dispose();
                        new teacher(prn).setVisible(true);
                        
                        JOptionPane.showMessageDialog(null, "You logged in successfully as techer..!!!");  
                    }
                    else if(admin.isSelected() && prn==999999999){
                        dispose();
                        new admin(prn).setVisible(true);
                        
                        JOptionPane.showMessageDialog(null, "You logged in successfully as admin..!!!");  
                    }
                    else{
                        JOptionPane.showMessageDialog(rootPane, "Error retrieving data","try again",JOptionPane.ERROR_MESSAGE);  
                    }
                    }
                        
                            
                    
                    else{
                        JOptionPane.showMessageDialog (null, "Password entered is wrong!!", "Try again", JOptionPane.ERROR_MESSAGE);
                        password.setText("");
                    }
                }
                else{
                    JOptionPane.showMessageDialog (null, "User not found!!", "Try again", JOptionPane.ERROR_MESSAGE);
                    username.setText("");
                    password.setText("");
                }        
        }
        catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_submitActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        username.setText("");
        password.setText("");
    }//GEN-LAST:event_resetActionPerformed

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton admin;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel label_password;
    private javax.swing.JLabel label_username;
    private javax.swing.JPasswordField password;
    private javax.swing.JButton reset;
    private javax.swing.JRadioButton student;
    private javax.swing.JButton submit;
    private javax.swing.JRadioButton teacher;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
