/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import database.DBConnection;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author mayan
 */
public class notices extends javax.swing.JFrame {

    /**
     * Creates new form notices
     */
    DBConnection db=new DBConnection();
    Connection conn=db.getMysqlConnect();
    public notices() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topic = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        description = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        updatenotice = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        mnotice = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        dnotice = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        ynotice = new javax.swing.JTextField();
        back = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(600, 440));
        setMinimumSize(new java.awt.Dimension(600, 440));
        setPreferredSize(new java.awt.Dimension(600, 440));
        getContentPane().setLayout(null);
        getContentPane().add(topic);
        topic.setBounds(10, 102, 555, 27);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel1.setText("Topic(60 letters)");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 64, 210, 30);

        description.setColumns(20);
        description.setLineWrap(true);
        description.setRows(5);
        description.setWrapStyleWord(true);
        jScrollPane1.setViewportView(description);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 160, 555, 189);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setText("Description(450 letters)");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 134, 180, 20);

        jLabel4.setFont(new java.awt.Font("Yu Gothic", 1, 24)); // NOI18N
        jLabel4.setText("ADD NOTICE");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(180, 10, 180, 40);

        updatenotice.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        updatenotice.setText("Update Notice");
        updatenotice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatenoticeActionPerformed(evt);
            }
        });
        getContentPane().add(updatenotice);
        updatenotice.setBounds(370, 360, 190, 30);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel5.setText("Date :-");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(350, 60, 40, 20);

        mnotice.setText("MM");
        mnotice.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                mnoticeFocusGained(evt);
            }
        });
        getContentPane().add(mnotice);
        mnotice.setBounds(470, 60, 34, 30);

        jLabel28.setText("/");
        getContentPane().add(jLabel28);
        jLabel28.setBounds(460, 60, 10, 30);

        dnotice.setText("DD");
        dnotice.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                dnoticeFocusGained(evt);
            }
        });
        getContentPane().add(dnotice);
        dnotice.setBounds(530, 60, 31, 30);

        jLabel29.setText("/");
        getContentPane().add(jLabel29);
        jLabel29.setBounds(514, 60, 10, 30);

        ynotice.setText("YYYY");
        ynotice.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ynoticeFocusGained(evt);
            }
        });
        getContentPane().add(ynotice);
        ynotice.setBounds(400, 60, 49, 30);

        back.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        back.setText("back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(469, 11, 80, 29);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces/back.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 630, 450);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void updatenoticeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatenoticeActionPerformed
        try {
            Statement stmt=conn.createStatement(); 
            String top=topic.getText();
            String desc=description.getText();
            String date=ynotice.getText()+"/"+mnotice.getText()+"/"+dnotice.getText();
            String qry="insert into notices(noticedate,description,topic) values('"+date+"','"+desc+"','"+top+"');";
            int rows=stmt.executeUpdate(qry);
            if(rows>0){
                    JOptionPane.showMessageDialog (null, "notice added successfully", "success", JOptionPane.INFORMATION_MESSAGE);
                    dispose();
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(notices.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_updatenoticeActionPerformed

    private void ynoticeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ynoticeFocusGained
        this.ynotice.setText("");
    }//GEN-LAST:event_ynoticeFocusGained

    private void mnoticeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mnoticeFocusGained
        this.mnotice.setText("");
    }//GEN-LAST:event_mnoticeFocusGained

    private void dnoticeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dnoticeFocusGained
        this.dnotice.setText("");
    }//GEN-LAST:event_dnoticeFocusGained

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        dispose();
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
   
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(notices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(notices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(notices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(notices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new notices().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JTextArea description;
    private javax.swing.JTextField dnotice;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField mnotice;
    private javax.swing.JTextField topic;
    private javax.swing.JButton updatenotice;
    private javax.swing.JTextField ynotice;
    // End of variables declaration//GEN-END:variables
}
