/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import database.DBConnection;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author mayan
 */
public class profile extends javax.swing.JFrame {

    /**
     * Creates new form profile
     */
            DBConnection db=new DBConnection();
            Connection conn=db.getMysqlConnect();
    public profile() {
        initComponents();
    }
    private int prn;
    public profile(int prn){
                try {
                    initComponents();
                    this.prn=prn;
                    Statement stmt1=conn.createStatement();
                    Statement stmt2=conn.createStatement();
                    String qry="select * from user where prn="+prn+";";
                    String qry1="select * from stud where prn="+prn+";";
                    ResultSet rs=stmt1.executeQuery(qry);
                    ResultSet rs1=stmt2.executeQuery(qry1);
                    if(rs.next()){
                    label_prn.setText(String.valueOf(prn));
                    fname.setText(rs.getString("fname"));
                    lname.setText(rs.getString("lname"));
                    branch.setText(rs.getString("branch"));
                    address.setText(rs.getString("addr"));
                    city.setText(rs.getString("city"));
                    state.setText(rs.getString("state"));
                    contact.setText(rs.getString("contact"));
                    mail.setText(rs.getString("email"));
                    dob.setText(rs.getString("dob"));
                    blood.setText(rs.getString("blood"));
                    }
                    if(rs1.next()){
                    fathername.setText(rs1.getString("fname"));
                    mothername.setText(rs1.getString("mname"));
                    category.setText(rs1.getString("category"));
                    admdate.setText(rs1.getString("adm_date"));
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(profile.class.getName()).log(Level.SEVERE, null, ex);
                }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_prn = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        fname = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fathername = new javax.swing.JLabel();
        mothername = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        dob = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lname = new javax.swing.JLabel();
        branch = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        category = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        admdate = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        address = new javax.swing.JTextArea();
        city = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        state = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        blood = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        contact = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        mail = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(780, 500));
        setMinimumSize(new java.awt.Dimension(780, 500));
        setPreferredSize(new java.awt.Dimension(780, 500));
        getContentPane().setLayout(null);

        label_prn.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        getContentPane().add(label_prn);
        label_prn.setBounds(220, 10, 290, 30);

        jLabel1.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        jLabel1.setText("PRN :-");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(150, 10, 80, 31);

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 48, 742, 10);

        jLabel2.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        jLabel2.setText("First Name :-");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(65, 76, 76, 24);

        fname.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        getContentPane().add(fname);
        fname.setBounds(160, 74, 142, 30);

        jLabel4.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        jLabel4.setText("Father's Name :-");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 170, 100, 24);

        fathername.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        getContentPane().add(fathername);
        fathername.setBounds(160, 164, 142, 30);

        mothername.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        getContentPane().add(mothername);
        mothername.setBounds(160, 210, 142, 30);

        jLabel7.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        jLabel7.setText("Mother's Name :-");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(40, 210, 100, 24);

        dob.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        getContentPane().add(dob);
        dob.setBounds(150, 250, 142, 30);

        jLabel9.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        jLabel9.setText("Date Of Birth :-");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(44, 250, 90, 24);

        jLabel10.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        jLabel10.setText("Last Name :-");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(70, 120, 80, 24);

        lname.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        getContentPane().add(lname);
        lname.setBounds(160, 114, 142, 30);

        branch.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        getContentPane().add(branch);
        branch.setBounds(150, 290, 142, 30);

        jLabel13.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        jLabel13.setText("Branch :-");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(50, 290, 60, 24);

        category.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        getContentPane().add(category);
        category.setBounds(150, 334, 142, 30);

        jLabel15.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        jLabel15.setText("Category :-");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(50, 340, 80, 24);

        admdate.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        getContentPane().add(admdate);
        admdate.setBounds(150, 380, 142, 40);

        jLabel17.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        jLabel17.setText("Addmission Date :-");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(30, 390, 110, 24);

        jLabel18.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        jLabel18.setText("Address :-");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(360, 70, 60, 24);

        address.setEditable(false);
        address.setColumns(20);
        address.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        address.setLineWrap(true);
        address.setRows(5);
        address.setWrapStyleWord(true);
        address.setEnabled(false);
        address.setFocusable(false);
        address.setOpaque(false);
        jScrollPane1.setViewportView(address);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(470, 70, 187, 106);

        city.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        getContentPane().add(city);
        city.setBounds(473, 199, 150, 24);

        jLabel20.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        jLabel20.setText("City :-");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(360, 200, 50, 24);

        state.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        getContentPane().add(state);
        state.setBounds(472, 240, 140, 24);

        jLabel22.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        jLabel22.setText("State :-");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(360, 240, 60, 24);

        blood.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        getContentPane().add(blood);
        blood.setBounds(470, 290, 142, 24);

        jLabel24.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        jLabel24.setText("Blood Group :-");
        getContentPane().add(jLabel24);
        jLabel24.setBounds(329, 290, 90, 24);

        contact.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        getContentPane().add(contact);
        contact.setBounds(470, 340, 142, 24);

        jLabel26.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        jLabel26.setText("Contact :-");
        getContentPane().add(jLabel26);
        jLabel26.setBounds(340, 340, 70, 24);

        mail.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        getContentPane().add(mail);
        mail.setBounds(470, 390, 214, 24);

        jLabel28.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        jLabel28.setText("Email ID :-");
        getContentPane().add(jLabel28);
        jLabel28.setBounds(340, 390, 60, 24);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces/wall.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 770, 480);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new profile(103217016).setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea address;
    private javax.swing.JLabel admdate;
    private javax.swing.JLabel blood;
    private javax.swing.JLabel branch;
    private javax.swing.JLabel category;
    private javax.swing.JLabel city;
    private javax.swing.JLabel contact;
    private javax.swing.JLabel dob;
    private javax.swing.JLabel fathername;
    private javax.swing.JLabel fname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel label_prn;
    private javax.swing.JLabel lname;
    private javax.swing.JLabel mail;
    private javax.swing.JLabel mothername;
    private javax.swing.JLabel state;
    // End of variables declaration//GEN-END:variables
}
