/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import database.DBConnection;
import java.awt.HeadlessException;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author mayan
 */
public class syllabuscheck extends javax.swing.JFrame {

    /**
     * Creates new form syllabuscheck
     */
    
            DBConnection db=new DBConnection();
            Connection conn=db.getMysqlConnect();
            private int prn;
    public syllabuscheck() {
        initComponents();
    }

        public syllabuscheck(int prn) {
        initComponents();
        this.prn=prn;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        subchoice = new javax.swing.JComboBox<>();
        syllabus = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        unit1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        unit2 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        unit3 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        unit4 = new javax.swing.JTextArea();
        back = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(1100, 770));
        setMinimumSize(new java.awt.Dimension(1100, 770));
        setPreferredSize(new java.awt.Dimension(1100, 770));
        getContentPane().setLayout(null);

        subchoice.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        subchoice.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Subject", "TOC", "DBMS", "CN", "SMD" }));
        getContentPane().add(subchoice);
        subchoice.setBounds(37, 21, 150, 30);

        syllabus.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        syllabus.setText("syllabus");
        syllabus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                syllabusActionPerformed(evt);
            }
        });
        getContentPane().add(syllabus);
        syllabus.setBounds(816, 11, 140, 30);

        jLabel3.setFont(new java.awt.Font("Yu Gothic", 1, 24)); // NOI18N
        jLabel3.setText("Unit 3 :-");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 440, 130, 27);

        jLabel4.setFont(new java.awt.Font("Yu Gothic", 1, 24)); // NOI18N
        jLabel4.setText("Unit 4 :-");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 610, 140, 27);

        jLabel1.setFont(new java.awt.Font("Yu Gothic", 1, 24)); // NOI18N
        jLabel1.setText("Unit 1 :-");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(70, 110, 130, 27);

        jLabel2.setFont(new java.awt.Font("Yu Gothic", 1, 24)); // NOI18N
        jLabel2.setText("Unit 2 :-");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 280, 130, 27);

        unit1.setEditable(false);
        unit1.setColumns(20);
        unit1.setFont(new java.awt.Font("Yu Gothic", 0, 13)); // NOI18N
        unit1.setRows(5);
        jScrollPane1.setViewportView(unit1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(253, 81, 709, 116);

        unit2.setEditable(false);
        unit2.setColumns(20);
        unit2.setFont(new java.awt.Font("Yu Gothic", 0, 13)); // NOI18N
        unit2.setRows(5);
        jScrollPane2.setViewportView(unit2);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(253, 241, 709, 116);

        unit3.setEditable(false);
        unit3.setColumns(20);
        unit3.setFont(new java.awt.Font("Yu Gothic", 0, 13)); // NOI18N
        unit3.setRows(5);
        jScrollPane3.setViewportView(unit3);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(253, 401, 709, 116);

        unit4.setEditable(false);
        unit4.setColumns(20);
        unit4.setFont(new java.awt.Font("Yu Gothic", 0, 13)); // NOI18N
        unit4.setRows(5);
        jScrollPane4.setViewportView(unit4);

        getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(253, 573, 709, 116);

        back.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        back.setText("back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(980, 10, 90, 30);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces/wall.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 1120, 710);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void syllabusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_syllabusActionPerformed
        try {
            int sub=subchoice.getSelectedIndex();
            String subject="";
            Statement stmt=conn.createStatement();
            switch(sub){
                case 1:{
                    subject="TOC";
                    break;
                }
                case 2:{
                    subject="DBMS";
                    break;
                }
                case 3:{
                    subject="CN";
                    break;
                }
                case 4:{
                    subject="SMD";
                    break;
                }
                default:JOptionPane.showMessageDialog(null, "Select Subject !!!!", "ERROR", 1);
            }
            String qry="select unit, topics from course where subject=\""+subject+"\";";
            ResultSet rs=stmt.executeQuery(qry);
            System.out.println(qry);
            while(rs.next()){
                switch(rs.getInt("unit")){
                    case 1:{
                        unit1.setText(rs.getString("topics"));
                        break;
                    }
                    case 2:{
                        unit2.setText(rs.getString("topics"));
                        break;
                    }
                    case 3:{
                        unit3.setText(rs.getString("topics"));
                        break;
                    }
                    case 4:{
                        unit4.setText(rs.getString("topics"));
                        break;
                    }
                    default: System.out.println("no course updated or available");
                }
            }
        } 
        catch (HeadlessException | SQLException ex) {
            java.util.logging.Logger.getLogger(syllabuscheck.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        
    }//GEN-LAST:event_syllabusActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
       
       
       dispose();
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(syllabuscheck.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(syllabuscheck.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(syllabuscheck.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(syllabuscheck.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new syllabuscheck().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JComboBox<String> subchoice;
    private javax.swing.JButton syllabus;
    private javax.swing.JTextArea unit1;
    private javax.swing.JTextArea unit2;
    private javax.swing.JTextArea unit3;
    private javax.swing.JTextArea unit4;
    // End of variables declaration//GEN-END:variables
}
