/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import database.DBConnection;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author mayan
 */
public class teacher extends javax.swing.JFrame {
            DBConnection db=new DBConnection();
            Connection conn=db.getMysqlConnect();
    /**
     * Creates new form teacher
     */
    private int prn;
    public teacher() {
        initComponents();
       
    }


    public teacher(int prn) {
        initComponents();
       
        this.prn=prn;
             try {
                    Statement stmt=conn.createStatement();
                    ResultSet rst=stmt.executeQuery("select u.fname,u.lname,t.subject,t.division from user u,teacher t where t.prn=u.prn and t.prn="+this.prn+";");
                    
                    if(rst.next()){
                        System.out.println(rst.getString("subject")+" "+rst.getString("fname")+" "+rst.getString("lname")+" "+Integer.toString(this.prn)+" "+rst.getString("division"));
                        label_subject.setText(rst.getString("subject"));
                        label_fname.setText(rst.getString("fname")+" "+rst.getString("lname"));
                        label_prn.setText(Integer.toString(this.prn));
                        label_div.setText(rst.getString("division"));

                    }
                } catch (SQLException ex) {
                    Logger.getLogger(teacher.class.getName()).log(Level.SEVERE, null, ex);
                }
    }
        /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chngepassword = new javax.swing.JDialog();
        old = new javax.swing.JTextField();
        newp = new javax.swing.JTextField();
        confirmnewp = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        chnge = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        options = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        label_fname = new javax.swing.JLabel();
        label_prn = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        label_subject = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        label_div = new javax.swing.JLabel();
        changepass = new javax.swing.JButton();
        tt = new javax.swing.JButton();
        proceed = new javax.swing.JButton();
        notice = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        teacherFunctionalities = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();

        chngepassword.setTitle("Change Password");
        chngepassword.setBounds(new java.awt.Rectangle(450, 350, 450, 270));

        jLabel4.setText("Old Password :-");

        jLabel5.setText("New Password :-");

        jLabel6.setText("Confirm New Password :-");

        chnge.setText("Change");
        chnge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chngeActionPerformed(evt);
            }
        });

        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout chngepasswordLayout = new javax.swing.GroupLayout(chngepassword.getContentPane());
        chngepassword.getContentPane().setLayout(chngepasswordLayout);
        chngepasswordLayout.setHorizontalGroup(
            chngepasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, chngepasswordLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(chngepasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(chngepasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(newp, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                    .addComponent(confirmnewp)
                    .addComponent(old))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, chngepasswordLayout.createSequentialGroup()
                .addContainerGap(240, Short.MAX_VALUE)
                .addComponent(clear)
                .addGap(18, 18, 18)
                .addComponent(chnge)
                .addGap(72, 72, 72))
        );
        chngepasswordLayout.setVerticalGroup(
            chngepasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chngepasswordLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(chngepasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(old, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(chngepasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newp, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(chngepasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmnewp, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(34, 34, 34)
                .addGroup(chngepasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chnge)
                    .addComponent(clear))
                .addGap(28, 28, 28))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 350));
        setMinimumSize(new java.awt.Dimension(800, 350));
        setPreferredSize(new java.awt.Dimension(800, 350));
        getContentPane().setLayout(null);

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 56, 770, 2);

        jLabel2.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        jLabel2.setText("Name:-");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(198, 14, 50, 31);

        label_fname.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        getContentPane().add(label_fname);
        label_fname.setBounds(242, 14, 157, 31);

        label_prn.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        getContentPane().add(label_prn);
        label_prn.setBounds(50, 14, 142, 30);

        jLabel14.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        jLabel14.setText("Subject:-");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(405, 14, 60, 31);

        label_subject.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        getContentPane().add(label_subject);
        label_subject.setBounds(462, 14, 100, 31);

        jLabel1.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        jLabel1.setText("PRN :-");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 14, 37, 31);

        jLabel15.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        jLabel15.setText("Division:-");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(586, 14, 60, 31);

        label_div.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        getContentPane().add(label_div);
        label_div.setBounds(654, 14, 110, 31);

        changepass.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        changepass.setText("Change password");
        changepass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changepassActionPerformed(evt);
            }
        });
        getContentPane().add(changepass);
        changepass.setBounds(505, 76, 194, 27);

        tt.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        tt.setText("View Timetable");
        tt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ttActionPerformed(evt);
            }
        });
        getContentPane().add(tt);
        tt.setBounds(505, 121, 194, 27);

        proceed.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        proceed.setText("GO");
        proceed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proceedActionPerformed(evt);
            }
        });
        getContentPane().add(proceed);
        proceed.setBounds(160, 230, 110, 39);

        notice.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        notice.setText("Add Notice");
        notice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noticeActionPerformed(evt);
            }
        });
        getContentPane().add(notice);
        notice.setBounds(505, 166, 194, 27);

        logout.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        logout.setText("Log out");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        getContentPane().add(logout);
        logout.setBounds(568, 225, 81, 25);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setText("Choose an Option");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(120, 90, 210, 28);

        teacherFunctionalities.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        teacherFunctionalities.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "mark attendance", "course update" }));
        getContentPane().add(teacherFunctionalities);
        teacherFunctionalities.setBounds(140, 157, 166, 29);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces/back1.jpg"))); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 800, 310);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void noticeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noticeActionPerformed
        notices n=new notices();
        n.setVisible(true);
    }//GEN-LAST:event_noticeActionPerformed

    private void proceedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proceedActionPerformed
        
       switch(teacherFunctionalities.getSelectedIndex()){
           case 0:
       
           new attendanceupdate(this.prn).setVisible(true);
       
               dispose();
               break;
           case 1:
               new courseupdate(this.prn).setVisible(true);
               dispose();
               break;
               
           default:
               JOptionPane.showMessageDialog(rootPane, "select atleast one option","try again",JOptionPane.INFORMATION_MESSAGE);
               break;
       }

        
    }//GEN-LAST:event_proceedActionPerformed

    private void ttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ttActionPerformed
        timetable t=new timetable();
        t.setVisible(true);
    }//GEN-LAST:event_ttActionPerformed

    private void changepassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changepassActionPerformed
        new passwordChange(this.prn).setVisible(true);
    }//GEN-LAST:event_changepassActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        old.setText("");
        newp.setText("");
        confirmnewp.setText("");
    }//GEN-LAST:event_clearActionPerformed

    private void chngeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chngeActionPerformed
        try {
            Statement stmt=conn.createStatement();
            String pass="";
            String qry="select pass from user where prn="+prn+";", qry1;
            ResultSet rs=stmt.executeQuery(qry);
            pass=rs.getString("pass");
            if(pass.equals(old.getText())){
                if(newp.getText().equals(confirmnewp.getText())){
                    qry1="update user set pass=\""+newp.getText()+"\" where prn="+prn+";";
                    stmt.executeUpdate(qry1);
                    JOptionPane.showMessageDialog(null, "Password chnged successfully...!!!", "DONE", 3);
                }
                else
                    JOptionPane.showMessageDialog(null, "New pasawords doesnt match...!!!", "ERROR", 1);
            }
            else
                JOptionPane.showMessageDialog(null, "Old password entered incorrect...!!!", "ERROR", 1);
        } catch (SQLException ex) {
            Logger.getLogger(teacher.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_chngeActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        dispose();
        new login().setVisible(true);
    }//GEN-LAST:event_logoutActionPerformed
///*
//    /**
//     * @param args the command line arguments
//     */
//  public static void main(String args[]) {
//////      /* Set the Nimbus look and feel */
//////////        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//////////        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//////////         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//////////         */
//////////        try {
//////////            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//////////                if ("Nimbus".equals(info.getName())) {
//////////                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//////////                    break;
//////////                }
//////////            }
//////////        } catch (ClassNotFoundException ex) {
//////////            java.util.logging.Logger.getLogger(teacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//////////        } catch (InstantiationException ex) {
//////////            java.util.logging.Logger.getLogger(teacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//////////        } catch (IllegalAccessException ex) {
//////////            java.util.logging.Logger.getLogger(teacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//////////        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//////////            java.util.logging.Logger.getLogger(teacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//////////        }
//////////        //</editor-fold>
//////
//////       /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//               
//                new teacher().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton changepass;
    private javax.swing.JButton chnge;
    private javax.swing.JDialog chngepassword;
    private javax.swing.JButton clear;
    private javax.swing.JTextField confirmnewp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel label_div;
    private javax.swing.JLabel label_fname;
    private javax.swing.JLabel label_prn;
    private javax.swing.JLabel label_subject;
    private javax.swing.JButton logout;
    private javax.swing.JTextField newp;
    private javax.swing.JButton notice;
    private javax.swing.JTextField old;
    private javax.swing.ButtonGroup options;
    private javax.swing.JButton proceed;
    private javax.swing.JComboBox<String> teacherFunctionalities;
    private javax.swing.JButton tt;
    // End of variables declaration//GEN-END:variables
}
