/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author mayan
 */
public class timetable extends javax.swing.JFrame {

    /**
     * Creates new form timetable
     */
    public timetable() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        divchoice = new javax.swing.JComboBox<>();
        tt = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 620));
        setMinimumSize(new java.awt.Dimension(800, 620));
        setPreferredSize(new java.awt.Dimension(800, 620));
        getContentPane().setLayout(null);

        divchoice.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        divchoice.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select division", "Division 1", "Division 2", "Division 3", "Division 4", "Division 5", "Division 6", "Division 7" }));
        getContentPane().add(divchoice);
        divchoice.setBounds(149, 12, 123, 30);

        tt.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        tt.setText("Show Schedule");
        tt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ttActionPerformed(evt);
            }
        });
        getContentPane().add(tt);
        tt.setBounds(354, 11, 180, 39);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 70, 830, 540);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces/wall.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 840, 630);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ttActionPerformed
        int div=divchoice.getSelectedIndex();
        switch(div){
            case 1:{
                jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Documents\\java_projects\\ERP\\ERP-master-20190922T135552Z-001\\ERP-master\\images\\panel1.png"));
                break;
            }
            case 2:{
                jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Documents\\java_projects\\ERP\\ERP-master-20190922T135552Z-001\\ERP-master\\images\\panel2.png"));
                break;
            }
            case 3:{
                jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Documents\\java_projects\\ERP\\ERP-master-20190922T135552Z-001\\ERP-master\\images\\\\panel3.png"));
                break;
            }
            case 4:{
                jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Documents\\java_projects\\ERP\\ERP-master-20190922T135552Z-001\\ERP-master\\images\\\\panel4.png"));
                break;
            }
            case 5:{
                jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Documents\\java_projects\\ERP\\ERP-master-20190922T135552Z-001\\ERP-master\\images\\\\panel5.png"));
                    break;
                }
            case 6:{
                jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Documents\\java_projects\\ERP\\ERP-master-20190922T135552Z-001\\ERP-master\\images\\panel6.png"));
                break;
            }
            case 7:{
                jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Documents\\java_projects\\ERP\\ERP-master-20190922T135552Z-001\\ERP-master\\images\\\\panel7.png"));
                break;
            }
            default: JOptionPane.showMessageDialog(null, "Select Division !!!!!", "ERROR", 1);
        }
        
    }//GEN-LAST:event_ttActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(timetable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(timetable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(timetable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(timetable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new timetable().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> divchoice;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JToggleButton tt;
    // End of variables declaration//GEN-END:variables
}
