/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import database.DBConnection;
import java.sql.Connection;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author mayan
 */
public class updateProfile extends javax.swing.JFrame {

    /**
     * Creates new form updateProfile
     */
    private int prn;
            DBConnection db=new DBConnection();
            Connection conn=db.getMysqlConnect();
    public updateProfile() {
        initComponents();
    }
    updateProfile(int prn){
        try {
            initComponents();
            this.prn=prn;
            if(addrtf.getText().isEmpty()||citytf.getText().isEmpty()||mailtf.getText().isEmpty()||contacttf.getText().isEmpty()||statetf.getText().isEmpty()||pintf.getText().isEmpty()){
                JOptionPane.showMessageDialog(rootPane,"fields cant be empty","try again",JOptionPane.WARNING_MESSAGE);
            }
            Statement stmt=conn.createStatement();
            String qry="update user set addr='"+addrtf.getText()+"',city='"+citytf.getText()+"',state='"+statetf.getText()+"',pincode="+pintf.getText()+",contact="+contacttf.getText()+",email='"+mailtf.getText()+" where prn="+this.prn+";";
            int rs=stmt.executeUpdate(qry);
            if(rs>0){
                JOptionPane.showMessageDialog(rootPane, "information updated successfully","SUCCESS",JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (SQLException ex) {
            Logger.getLogger(updateProfile.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        addrtf = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        citytf = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        statetf = new javax.swing.JTextField();
        pintf = new javax.swing.JTextField();
        contacttf = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        mailtf = new javax.swing.JTextField();
        update = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(500, 500));
        setMinimumSize(new java.awt.Dimension(500, 500));
        setPreferredSize(new java.awt.Dimension(500, 500));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Address :-");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(53, 51, 62, 15);

        addrtf.setColumns(20);
        addrtf.setLineWrap(true);
        addrtf.setRows(5);
        addrtf.setWrapStyleWord(true);
        addrtf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addrtfMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(addrtf);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(168, 38, 211, 96);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("City :-");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(53, 178, 37, 15);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("State :-");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(53, 216, 47, 15);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Pincode :-");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(53, 254, 61, 15);

        citytf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                citytfFocusGained(evt);
            }
        });
        getContentPane().add(citytf);
        citytf.setBounds(168, 176, 153, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Contact no :-");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(53, 292, 82, 15);

        statetf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                statetfFocusGained(evt);
            }
        });
        getContentPane().add(statetf);
        statetf.setBounds(168, 214, 153, 20);

        pintf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pintfFocusGained(evt);
            }
        });
        getContentPane().add(pintf);
        pintf.setBounds(168, 252, 153, 20);

        contacttf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                contacttfFocusGained(evt);
            }
        });
        getContentPane().add(contacttf);
        contacttf.setBounds(168, 290, 153, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Email :-");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(53, 330, 44, 15);

        mailtf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                mailtfFocusGained(evt);
            }
        });
        getContentPane().add(mailtf);
        mailtf.setBounds(168, 328, 200, 20);

        update.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        getContentPane().add(update);
        update.setBounds(160, 390, 140, 31);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces/back1.jpg"))); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(-10, -20, 560, 510);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addrtfMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addrtfMouseClicked
        addrtf.setText("");
    }//GEN-LAST:event_addrtfMouseClicked

    private void citytfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_citytfFocusGained
        citytf.setText("");
    }//GEN-LAST:event_citytfFocusGained

    private void statetfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_statetfFocusGained
        statetf.setText("");
    }//GEN-LAST:event_statetfFocusGained

    private void pintfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pintfFocusGained
        pintf.setText("");
    }//GEN-LAST:event_pintfFocusGained

    private void contacttfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_contacttfFocusGained
        contacttf.setText("");
    }//GEN-LAST:event_contacttfFocusGained

    private void mailtfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mailtfFocusGained
        mailtf.setText("");
    }//GEN-LAST:event_mailtfFocusGained

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        try {
            String addr=addrtf.getText();
            String city=citytf.getText();
            String state=statetf.getText();
            String mail=mailtf.getText();
            String contact=contacttf.getText();
            int pin=Integer.parseInt(pintf.getText());
            Statement stmt=conn.createStatement();
            String qry="update user set addr=\""+addr+"\", city=\""+city+"\", state=\""+state+"\", email=\""+mail+"\", pincode="
                    +pin+", contact=\""+contact+"\" where prn="+prn+";";
            stmt.executeUpdate(qry);
            JOptionPane.showMessageDialog(null, "Update successful !!!!!", "Done", 3);
        } catch (SQLException ex) {
            Logger.getLogger(updateProfile.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_updateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(updateProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(updateProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(updateProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(updateProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new updateProfile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea addrtf;
    private javax.swing.JTextField citytf;
    private javax.swing.JTextField contacttf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField mailtf;
    private javax.swing.JTextField pintf;
    private javax.swing.JTextField statetf;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
